#import "MacControlRoutingPolicy.hpp"

BOOL MacControlIsReadQueueMethod(NSString* method) {
    static NSSet<NSString*>* readMethods = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        readMethods = [NSSet setWithArray:@[
            @"workspace.grep",
            @"search.text",
            @"search.files",
            @"search.todo",
            @"search.diagnostics",
            @"diagnostics.list",
            @"diagnostics.summary",
            @"diagnostics.cluster",
            @"diagnostics.forFile",
            @"workspace.listFiles",
            @"recovery.scan",
            @"file.read",
            @"file.readRange",
            @"file.readAround",
            @"file.getChunks",
            @"file.stat",
            @"git.status",
            @"git.diff",
            @"analysis.workspaceSummary",
            @"analysis.searchRanked",
            @"analysis.fileSummary",
            @"analysis.relatedFiles",
            @"symbols.document",
            @"symbols.outline",
            @"symbols.activeDocument",
            @"symbols.references",
            @"editor.getActiveFile",
            @"editor.getOpenFiles",
            @"editor.getText",
            @"editor.getSelection",
            @"diff.workspaceInfo",
            @"diff.stats",
            @"diff.file",
            @"diff.chunk",
            @"diff.hunks",
            @"diff.current",
            @"diff.staged",
            @"diff.unstaged",
            @"diff.summary",
            @"buffers.snapshot",
            @"buffers.dirty",
            @"buffers.active",
            @"buffers.unsavedDiff",
            @"changes.current",
            @"changes.summary",
            @"patch.chunk",
            @"patch.hunks",
            @"problems.list",
            @"language.diagnostics",
            @"terminal.status",
            @"terminal.jobs",
            @"terminal.history",
            @"terminal.getOutput",
            @"session.info",
            @"session.workflowState",
            @"session.recentCommands",
            @"session.lastSearches"
        ]];
    });
    return [readMethods containsObject:method];
}
